/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cheng_cplusplustest_MainActivity */

#ifndef _Included_com_example_cheng_cplusplustest_MainActivity
#define _Included_com_example_cheng_cplusplustest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cheng_cplusplustest_MainActivity
 * Method:    getString2Fromc
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_cheng_cplusplustest_MainActivity_getString2Fromc
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_cheng_cplusplustest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cheng_cplusplustest_MainActivity_stringFromJNI
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_example_cheng_cplusplustest_MainActivity_accessField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_cheng_cplusplustest_MainActivity_accessStaticField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_cheng_cplusplustest_MainActivity_accessMethod
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_cheng_cplusplustest_MainActivity_accessStaticMethod
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
